"""initial tables

Revision ID: 5a0edc518305
Revises:
Create Date: 2024-02-23 18:08:47.089341

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a0edc518305"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=88), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("state", sa.Enum("Ongoing", "Finished", "Archived", name="todostate"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_todos_id", "todos", ["id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("todo_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["todo_id"],
            ["todos.id"],
        ),
        sa.PrimaryKeyConstraint("todo_id", "tag"),
    )
    op.create_index("idx_tags_todo_id", "tags", ["todo_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tags_todo_id", table_name="tags")
    op.drop_table("tags")
    op.drop_index("idx_todos_id", table_name="todos")
    op.drop_table("todos")
    # ### end Alembic commands ###
