name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python 3.12
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
          version: 1.7.1
      
      - name: Install dependencies
        run: poetry install --no-interaction --all-extras

      - name: Run Tests
        run: |
          poetry run pytest

      - name: Run Mypy
        run: |
          poetry run mypy
